name: Lint & Test

on: [push]

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v2

    - name: Install toolchain
      uses: actions-rs/toolchain@v1.0.7
      with:
          toolchain: stable
          components: clippy, rustfmt
          override: true

    - name: Generate lockfile
      uses: actions-rs/cargo@v1
      with:
        command: generate-lockfile

    - uses: actions/cache@v2
      env:
        cache-name: lint
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ env.cache-name }}
          ${{ runner.os }}-cargo-

    - name: Run Clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features

    - name: Run Rustfmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v2

    - name: Install toolchain
      uses: actions-rs/toolchain@v1.0.7
      with:
          toolchain: stable
          override: true

    - name: Generate lockfile
      uses: actions-rs/cargo@v1
      with:
        command: generate-lockfile

    - uses: actions/cache@v2
      env:
        cache-name: test
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ env.cache-name }}
          ${{ runner.os }}-cargo-

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
